exclude: 'conf|input|docs|logs|models|output|ucr/utils/dict|ucr/utils/fonts'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending      
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=15000]

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: []
        files: .

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            '--in-place',
            '--remove-unused-variable',
            '--ignore-init-module-imports',
            '--remove-all-unused-imports',
          ]
          
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.5.3
    hooks:
      - id: isort
        args: []
        files: .

  - repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
      - id: nbstripout
        files: '.ipynb'

  - repo: local
    hooks:
      - id: requirements.txt
        name: Generate requirements.txt
        entry: poetry export
        args:
          [
            '-f',
            'requirements.txt',
            '-o',
            'requirements.txt',
            '--without-hashes',
          ]
        pass_filenames: false
        language: system
        files: 'poetry.lock'
