# Project Info
site_name: Universal Character Recognizer (UCR)
site_url: https://docyard.ai/UCR
site_description: Universal Character Recognizer
site_author: Abhigyan Raman

#Repository
repo_url: https://github.com/DocYardAI/UCR
repo_name: DocYardAI/UCR
edit_uri: "" #disables edit button

# Copyright
copyright: Copyright (c) 2021 DocYard Authors

# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DocYard_ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/docyard
    - icon: fontawesome/brands/github
      link: https://github.com/DocYard-ai
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCOj4z9JJg10icPXIQl2bKPg
    - icon: fontawesome/solid/paper-plane
      link: mailto:abhigyan@docyard.ai

# Configuration
theme:
  name: material
  logo: static/images/Groupicon.png
  favicon: static/images/Groupicon.ico
  palette:
    scheme: ucr
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences: # nest code and content inside alerts# nest code and content inside alerts
      preserve_tabs: true 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format 
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite: # inline code highlights
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - pymdownx.tabbed # content tabs
  - footnotes
  - def_list
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: DocYard-ai
      repo: UCR
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

# Extensions
# markdown_extensions:
#   - meta:
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg
#   - admonition: # alerts
#   - pymdownx.details: #  collapsible alerts
#   - pymdownx.superfences:
#       preserve_tabs: true
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_code_format
#         - name: math
#           class: arithmatex
#           format: !!python/name:pymdownx.arithmatex.fence_mathjax_format # nest code and content inside alerts
#   - attr_list: # add HTML and CSS to Markdown elements
#   - pymdownx.inlinehilite:
#       custom_inline:
#         - name: math
#           class: arithmatex
#           format: !!python/name:pymdownx.arithmatex.inline_mathjax_format # inline code highlights
#   - pymdownx.keys: # show keystroke symbols
#   - pymdownx.snippets: # insert content from other files
#   - pymdownx.tabbed: # content tabs
#   - footnotes:
#   - def_list:
#   - pymdownx.smartsymbols:
#   - pymdownx.mark:
#   - pymdownx.magiclink:
#       hide_protocol: true
#       repo_url_shortener: true
#       repo_url_shorthand: true
#       social_url_shorthand: true
#       social_url_shortener: true
#       user: DocYard-ai
#       repo: UCR
#       normalize_issue_symbols: true
#   - pymdownx.arithmatex: # mathjax
#       generic: true
#   - pymdownx.tasklist:
#       custom_checkbox: true
#       clickable_checkbox: true
#   - codehilite:
#   - pymdownx.highlight:
#       use_pygments: true
#   - toc:
#       toc_depth: 4

# Plugins
plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
      watch:
        - ucr

# Extra CSS
extra_css:
  - static/css/custom.css

# Extra JS
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home:
      - UCR: index.md
  - Installation: getting_started.md
  - Tutorials: coming_soon.md
  - How to Contribute!: coming_soon.md
    # - Config: ucr/config.md
    # - Data: ucr/data.md
    # - Models: ucr/models.md
    # - Training: ucr/train.md
    # - Inference: ucr/predict.md
    # - Utilities: ucr/utils.md