defaults:
    - preprocess: 
        rec_ctc
    - architecture: 
        rec_ppocr_server
    - postprocess: 
        rec_ctc
    - hydra/job_logging: custom
    - hydra/output: custom 

job_name: rec_infer
level: INFO
batch_size: 8
device: cuda
lang: ch_sim
max_text_length: 25
use_space_char: True
whitelist: "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]_abcdefghijklmnopqrstuvwxyz{|}~—‘’“”"
blacklist: 

input: test/
model_location: 
# models/rec/multi_language/rec_ch_sim_ppocr_server.pt
font_path: 
# ucr/utils/fonts/only_en.ttf
char_dict_location: 
# ucr/utils/dict/ch_sim_dict.txt
